name: .NET 5 Console

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: NololCompiler.sln                          # Replace with your solution name, i.e. MyWpfApp.sln.
      Publish_Path: src\bin\Release\net5.0\publish              # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Project_Path: src\NololCompiler.csproj                    # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Restore and Publish Application
      run: dotnet publish $env:Project_Path --configuration $env:Configuration -f net5.0 --self-contained true --runtime win-x64 --output $env:Publish_Path
      env:
        Configuration: ${{ matrix.configuration }}

    ## Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    #- name: Upload publish artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: nololcompiler-win-x64
    #    path: ${{ env.Publish_Path  }}

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
       repo_token: "${{ secrets.GITHUB_TOKEN }}"
       automatic_release_tag: "latest"
       prerelease: true
       title: "Development Build"
       files: ${{ env.Publish_Path }}/nololcompiler.exe
       path: ${{ env.Publish_Path  }}
            
