name: Release on new Tag

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.tar.gz,*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
